export * from './Content'
export { default as About } from './About'
export { default as SimulatorBridge } from './SimulatorBridge'
export { default as Cta } from './Cta'
export { default as FinalCta } from './FinalCta'
export { default as HomeFaq } from './HomeFaq'
export { default as Positioning } from './Positioning'
export { default as PreFooter } from './PreFooter'
export { default as RegionalPresence } from './RegionalPresence'
export { default as Sustainability } from './Sustainability'
export { default as Segments } from './Segments'

export { default as Hero } from './Hero'
export { default as Solutions } from './Solutions'
export { default as Stats } from './Stats'
export { default as Testimonials } from './Testimonials'
